### ISSUE TITLE
Separate build jobs (and pipelines) for each talend harvester

### ISSUE THREAD

**Issue by jkburges** [aodn/chef#169]
It's currently pretty hard to debug problems with everything ending up in together.  Also, archived artifacts seem to be shipped around for _all_ harvesters.

**Comment by pblain** [comment]
I think we have this now

**Comment by lbesnard** [comment]
@pblain I actually don't think this is the case. See issue we've been having with @anguss00 lately

**Comment by pblain** [comment]
@lbesnard - it's covered by this right? https://github.com/aodn/backlog/issues/526 .. or something else??

**Comment by lbesnard** [comment]
Yes you're right
