### ISSUE TITLE
Provisioning of PO Box requires access to another private repo

### ISSUE THREAD

**Issue by jkburges** [aodn/chef#180]
This was reported by @stevenvandervalk.

When running the `bin/po-box.sh` script, the following errors occurs:

```
Cloning into 'src/data-services'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

due to lack of access to https://github.com/aodn/data-services

There are a few questions/options:
- does that repo _need_ to be private (all production passwords should be stored elsewhere, no?)
- if yes, then we should add handling, somehow, for this case

**Comment by pblain** [comment]
Don't know if this is still an issue but closing as we are likely ending support for PO Box.
