### ISSUE TITLE
Parallel deployment may not deploy config file

### ISSUE THREAD

**Issue by danfruehauf** [aodn/chef#225]
Parallel deployment has been on edge and systest for a very long time, yet it still has a problem which I do not know how to reproduce.
## What happens
- Config file is missing. Under the tomcat directory the following file should be present (considering `1452151229` is the timestamp of the current deployed version):

```
$ ls -l conf/Catalina/localhost/imos123##1452151229.xml
-rw-r--r-- 1 tomcat7 tomcat7 1543 Jan  8 13:56 conf/Catalina/localhost/imos123##1452151229.xml
```

Once I know how to reproduce it systematically I'll definitely fix it. For the time being I've seen it happen once out of hundreds of deployments on edge.

**Comment by danfruehauf** [comment]
If this happens, the easy way to mitigate it is to delete the war in the webapps directory and the corresponding directory. For instance on portal-systest:
```
cd /mnt/ebs/tomcat7/portal_imos123/webapps && sudo rm -rf imos123*
```

Then provision again the node. Should fix things.

**Comment by anguss00** [comment]
Thanks @danfruehauf

**Comment by pblain** [comment]
@anguss00 - please re-open if this is still an issue
