### ISSUE TITLE
Changes to sql extensions aren't deployed

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#237]
Refer https://github.com/aodn/harvest_sql_library/pull/7

Changes merged in this PR have not been deployed to 14-nsp-mel or 2-aws-syd automatically by chef.

This used to happen and there still seems to be code in the postgres cookbook to deploy them but it doesn't seem to be being triggered:

https://github.com/aodn/chef/blob/master/cookbooks/imos_postgresql/definitions/imos_postgresql_database_with_schemas.rb#L556

**Comment by pblain** [comment]
Move to backlog

**Comment by jonescc** [comment]
Main reason for this not being triggered was:  https://github.com/aodn/chef/blob/master/cookbooks/imos_postgresql/recipes/official_postgresql.rb#L301

Database updates are only applied if a change is detected between the cached database state and database databags.  The database databags don't include git extension changes and so the database definition responsible for making changes to the database was not invoked, but its the database definition which updates extensions.

To fix we could pull extension maintenance out of the database definition, trigger database updates on extension changes checking cached state/speed up database maintenance operations.

To manually trigger an update before then, we would need to remove the database cached state file (i.e. /var/chef/cache/imos_postgresql/state/main-databases.json) and trigger a git sync change as the prior sync change has already been processed (e.g. by deleting the /var/chef/cache/postgresql_extension_support directory).

No github extension changes have been processed since updates have been based on the cached databag state.  These are the only differences

```
commit 04d2c69acf2879fe9944fb4370018ba35a3e77cb
Merge: 819b3c3 fbfa07a
Author: Craig Jones <Craig.Jones@utas.edu.au>
Date:   Mon Aug 22 12:17:51 2016 +1000

    Merge pull request #9 from aodn/postgis-dependency
    
    Add explicit postgis dependency to enforce ordering on dump/restore a…

commit fbfa07a49af86477cd3e3fb0f2eb5ce3819c7f80
Author: julian1 <julian.atkinson71@gmail.com>
Date:   Mon Aug 22 12:16:41 2016 +1000

    Add explicit postgis dependency to enforce ordering on dump/restore actions

commit 819b3c3e5d12166de50ee0a47f58fe8f7c9800e0
Merge: b99d3b0 a8542b7
Author: julian1 <jfca@utas.edu.au>
Date:   Thu Jan 28 10:26:20 2016 +1100

    Merge pull request #8 from aodn/postgis_2_2
    
    Use postgis 2.2

commit a8542b73168e4f1e5ec9fb7127aa876f865618ed
Author: Dan Fruehauf <malkodan@gmail.com>
Date:   Wed Jan 27 17:27:24 2016 +1100

    Use postgis 2.2
    
    Better aliases for function MakePoint, so it does not depend on
    installed postgis version.

commit b99d3b061ec85e9924d83144555e96614f82b4c2
Merge: 47524b0 11a3472
Author: Dan Fruehauf <malkodan@gmail.com>
Date:   Mon Jan 18 16:34:40 2016 +1100

    Merge pull request #7 from aodn/add-ids-to-polygons
    
    Fix XSD validation error for generated polygons by adding a unique id…

commit 11a3472d060cad1240faa647c45b32c9cc39f703
Author: Craig Jones <Craig.Jones@utas.edu.au>
Date:   Mon Jan 18 12:39:19 2016 +1100

    Fix XSD validation error for generated polygons by adding a unique id to each polygon

```

**Comment by julian1** [comment]
The elephant in the room - is that provisioning now entirely disregards the node definition for lots of database items - users, schemas, components etc.

If the the user has to ssh to the VM to manually effect a change - before running chef -  then chef no longer captures the domain knowledge needed to manage the infrastructure.

**Comment by jonescc** [comment]
If we are going to continue to use chef to provision databases in the foreseeable future then we should probably fix this properly - remove use of cached state/improve db provisioning performance.

**Comment by julian1** [comment]
Keep in mind - if we move to RDS - we can't use Chef.

Also, with RDS, we cannot use postgres extensions to manage our code.

**Comment by lwgordonimos** [comment]
Yes I agree. I think it needs to be either:

1. Chef **OR** RDS provisions an empty Postgres installation and *something* else handles it from there exclusively through the Postgres endpoint 
1. Chef provisions everything

@julian1 I really like the idea of option 1 with the work you were doing... as long as there was a reasonable way to replace the extensions.

I feel like the second option is a bit of a dead end in the longer term, being totally non-portable.

**Comment by pblain** [comment]
Leaving until a decision is made.  Labelled "Won't Fix"

**Comment by jonescc** [comment]
Note that even if the existing caching code was removed or modified to correctly identify when an extension had been modified and needed to be deployed, the current mechanism for redeploying extensions doesn't work - it drops the extension and then re-adds it.  This causes an exception to be thrown in a populated database where other objects depend on objects defined in the schema.

```
* ruby_block[main-harvest-public-imos-custom-extension-reload-from-repo] action create[2017-05-08T13:55:50+10:00] FATAL: ShellOut failed 'ERROR:  cannot drop extension imos because other objects depend on it
DETAIL:  view argo.float_cycle depends on function make_shortest_line(geometry,geometry)
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

The extensions feature supports upgrading between different versions of an extension usig upgrade scripts but we haven't implemented that functionality.

Also note that some of the changes above that were never deployed to production because of this issue were to fix the ordering of postgis/imos extension backups/restores.
