### ISSUE TITLE
new user-account for demo-laptop with private keys for review presentations and server access

### ISSUE THREAD

**Issue by julian1** [aodn/chef#287]
And/or a dedicated jump-box with password access to enable ssh.

It's pretty awful from a security standpoint though.

**Comment by pblain** [comment]
I think Jesus has saved us

**Comment by anguss00** [comment]
Praise be!!
![jeethus](https://cloud.githubusercontent.com/assets/5964166/22537790/80099418-e961-11e6-9ea1-d8ce2dae083f.jpg)
