### ISSUE TITLE
Reduce Chef control of geoserver-config config.ftl

### ISSUE THREAD

**Issue by pmbohm** [aodn/chef#301]
### What  is happening
- Changes to the geoserver-config config.ftl file are not being seen on the server.
  '<#assign baseurlDataServerS3Listing = "http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=" >'
  is not being deployed from  the https://github.com/aodn/geoserver-config repo
- private-sample/data_bags/imos_webapps_geoserver_config_ftl/default.json contains unused variables
### What should happen
- Chef should deploy what is the https://github.com/aodn/geoserver-config repo
- Chef should override values 'only' where required
- The config.ftl file should include text inside that informs developers that Chef is overridding variables

**Comment by pmbohm** [comment]
I have created /mnt/ebs/geoserver_123/workspaces/imos/config.ftl on 1-aws-syd that will need to be removed

**Comment by lwgordonimos** [comment]
Fixed by: https://github.com/aodn/chef-private/pull/2150
