### ISSUE TITLE
Non-IMOS builds failing

### ISSUE THREAD

**Issue by markhepburn** [aodn/chef#311]
Hi guys,

IMAS have a number of portal instances that are cooked nightly using these cookbooks.

As part of that, we use the portal and geoserver builds from your jenkins build server (we have our own geonetwork build).  I've just been alerted that these cooks are failing (someone was trying to run them manually), and after investigating it's because those artefacts aren't available any more.  I just checked and there don't seem to be any public builds at all any more.

Would that be related to #289?  Is there an ETA on when they'll be available again, or are they permanently offline?

**Comment by anguss00** [comment]
Hi @markhepburn,
Apologies for that, we've just locked down the builds in jenkins temporarily while we provision a new slave node. It should be up and running before 5 tonight. So yeah, related to #289

**Comment by markhepburn** [comment]
Thanks @anguss00

**Comment by lwgordonimos** [comment]
@markhepburn Hi Mark, the artifacts are now available on Jenkins again.

**Comment by markhepburn** [comment]
Thanks @lwgordonimos , looks better now
