### ISSUE TITLE
data.aodn.org.au does not offer HTTPS

### ISSUE THREAD

**Issue by pmbohm** [aodn/chef#340]
### What happens

Because data.aodn.org.au does not offer HTTPS, loading images from data.aodn.org.au into secure web pages (ie AUV) causes console errors and gives the impression to users that the site is insecure.

![screen shot 2016-07-06 at 9 48 04 am](https://cloud.githubusercontent.com/assets/1066981/16603991/156da37c-4364-11e6-8bc4-6829b085474f.png)
### What should happen

https://data.aodn.org.au should be offered

**Comment by pmbohm** [comment]
@lbesnard Could you please change the `auv_image_vw` content.ftl to use  the S3 base URL configured in config.ftl ?
@pblain Is it ok to use S3 URL's directly?

**Comment by lbesnard** [comment]
well I'm a bit confused, it already uses it, see
https://github.com/aodn/geoserver-config/blob/master/workspaces/config.ftl#L3
https://github.com/aodn/geoserver-config/blob/master/workspaces/imos/JNDI_auv_viewer/auv_images_vw/content.ftl#L5

**Comment by pmbohm** [comment]
@lbesnard Yes your 100% right
Trapped once again by chef!!!
Chef issue https://github.com/aodn/chef/issues/301 must be fixed

**Comment by pblain** [comment]
@pmbohm , @lbesnard - Chef issue https://github.com/aodn/chef/issues/301 is closed - so closing this too.
