### ISSUE TITLE
Local artifact deployment now requires md5 file

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#370]
I make use of local artifact deployment extensively for testing modified code in vagrant.

e.g.

                "apps": [
                    {
                        "name":               "geoserver",
                        "artifact":           "/mnt/source-code/geoserver-build/src/main/target/geoserver-1.0.0-imos.war",
                        "custom_def":         "geoserver",
                        "data_bag":           "geoserver_123",
                        "jndis":              [ "harvest_read_123_1_nec_hob" ],

This recently stopped working for me - seems an md5 file is required which is something that jenkins normally adds (I don't involve jenkins in local builds):

```
==> 1-nec-hob.emii.org.au: [2016-07-27T08:38:52+10:00] WARN: Retrying 1/3 '/mnt/source-code/geoserver-build/src/main/target/geoserver-1.0.0-imos.war.md5'
==> 1-nec-hob.emii.org.au: [2016-07-27T08:38:54+10:00] WARN: Retrying 2/3 '/mnt/source-code/geoserver-build/src/main/target/geoserver-1.0.0-imos.war.md5'
==> 1-nec-hob.emii.org.au: [2016-07-27T08:38:56+10:00] WARN: Retrying 3/3 '/mnt/source-code/geoserver-build/src/main/target/geoserver-1.0.0-imos.war.md5'
==> 1-nec-hob.emii.org.au: [2016-07-27T08:38:58+10:00] FATAL: Could not access '/mnt/source-code/geoserver-build/src/main/target/geoserver-1.0.0-imos.war.md5'
=
```

Perhaps return this to not requiring an md5 file for local artifacts?

**Comment by lwgordonimos** [comment]
@jonescc Thanks, this is a bug for local files introduced by https://github.com/aodn/chef/pull/357. It does not consider local files, and obviously needs to!
