### ISSUE TITLE
PO box provision fails trying to download s3fs from googlecode

### ISSUE THREAD

**Issue by mhidas** [aodn/chef#387]
Looks like it's trying to install s3fs from an old google code site. That repo has been moved to https://github.com/s3fs-fuse/s3fs-fuse, though I'm guessing this is actually not needed for the PO box.

```
==> po:   * remote_file[/tmp/s3fs-1.61.tar.gz] action create_if_missing
==> po: [2016-08-26T09:38:55+10:00] INFO: HTTP Request Returned 404 Not Found: 
==> po: [2016-08-26T09:38:55+10:00] WARN: remote_file[/tmp/s3fs-1.61.tar.gz] cannot be downloaded from http://s3fs.googlecode.com/files/s3fs-1.61.tar.gz: 404 "Not Found"
==> po: 
==> po:     
==> po:     
==> po: ================================================================================
==> po:     Error executing action `create_if_missing` on resource 'remote_file[/tmp/s3fs-1.61.tar.gz]'
==> po:     ================================================================================
```

**Comment by lwgordonimos** [comment]
Have submitted a PR to the upstream cookbook, https://github.com/hw-cookbooks/s3fs-fuse

If it can't be resolved there, we will need to fork it but thought I'd try that first.

**Comment by mhidas** [comment]
Looks like there's a similar PR there (https://github.com/hw-cookbooks/s3fs-fuse/pull/12) that's been waiting a while...

**Comment by lwgordonimos** [comment]
Oops, totally missed that one. Looks like we may need to fork unless the fact that it now literally doesn't work prompts a merge.

**Comment by lwgordonimos** [comment]
https://github.com/aodn/chef/pull/388

@mhidas try your PO box provision out of this chef branch

**Comment by julian1** [comment]
Hitting the same thing, trying to provision Jenkins. It worked yesterday...

```
  * apt_package[fuse-utils] action install (up to date)
  * apt_package[libcurl4-openssl-dev] action install
    - install version 7.22.0-3ubuntu4.16 of package libcurl4-openssl-dev
  * apt_package[libxml2-dev] action install (up to date)
  * apt_package[mime-support] action install (up to date)
  * remote_file[/tmp/s3fs-1.74.tar.gz] action create_if_missing[2016-08-26T13:49:40+10:00] WARN: remote_file[/tmp/s3fs-1.74.tar.gz] cannot be downloaded from http://s3fs.googlecode.com/files/s3fs-1.74.tar.gz: 404 "Not Found"
```

**Comment by julian1** [comment]
https://github.com/aodn/chef/pull/388

**Comment by julian1** [comment]
Worked for me.

**Comment by pblain** [comment]
Discussed at planning - closing
