### ISSUE TITLE
Don't want to use configured s3 credentials in vagrant?

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#410]
Currently if someone runs up systest of production geoserver wps nodes in vagrant, any wps requests will write artifact output to the configured s3 storage location - i.e. systest or prod locations.  

This is not ideal.   With jndi connection details we replace configured db details with localhost to prevent accidentlly impacting production.  We should perhaps do somehting similar with s3 access

**Comment by lwgordonimos** [comment]
Yes, excellent point. This needs to be mocked somehow.

**Comment by anguss00** [comment]
Yep, agreed. I'm super paranoid about this, had to do end to end testing yesterday and blew away my box after so it wouldn't affect prod.

**Comment by lwgordonimos** [comment]
Fixed by https://github.com/aodn/chef/pull/411
