### ISSUE TITLE
FTP uploaders shouldn't be able to create sub-directories 

### ISSUE THREAD

**Issue by mhidas** [aodn/chef#418]
People uploading data via FTP should only be able to upload files into the designated chef-managed directories. #212 was supposed to enforce this, but it doesn't seem to be working. One of the ANMN uploaders just created a subdir in `/mnt/ebs/incoming/ANMN/NRS/` (called `NRSNSI` - I'll move the contents but leave the directory there in case it provides any helpful clues).

**Comment by lwgordonimos** [comment]
@mhidas Interesting... will need to check out some logs etc to see what may have happened, and try to replicate.

**Comment by akashisama** [comment]
Can't replicate. Hopefully if this happens again we'll get on it it sooner so we still have some logs to look at.
