### ISSUE TITLE
Pipeline faulty when chef is deploying new code

### ISSUE THREAD

**Issue by ggalibert** [aodn/chef#440]
The 07 Dec, during 2 minutes at around 17:00, all ACORN files that were being processed by the pipeline have been sent to the error directory with the following error message in their log files:
> /mnt/ebs/talend/bin/talend-trigger:151: syntax error, unexpected ')', expecting '='
> /mnt/ebs/talend/bin/talend-trigger:172: syntax error, unexpected kEND, expecting $end

Today I have moved the files from error to incoming and they have been processed successfully.

@jonescc believes that the harvester might have tried running while new code was being deployed (Craig correct me if I'm wrong).

This issue is not critical but for consistent regular or mass upload like the ACORN data it would be useful to have a "safety net" so that for example the pipeline is being paused when chef is cooking?

**Comment by pblain** [comment]
Closing as this is now part of the pipeline project requirements.
