### ISSUE TITLE
Unable to provision 13-aws-syd

### ISSUE THREAD

**Issue by bhasin85** [aodn/chef#470]
This is probably happening after upgrading to jenkins 2. In config.xml the following code have been changed

```
  <authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
    <denyAnonymousReadAccess>true</denyAnonymousReadAccess>
  </authorizationStrategy>
```

which is giving following error.

> STDERR: ERROR: anonymous is missing the Overall/Read permission

**Comment by anguss00** [comment]
![burns](https://cloud.githubusercontent.com/assets/5964166/24089053/e3e5f16e-0d85-11e7-946a-cdac9a6583dd.gif)
