### ISSUE TITLE
po box occasionally fails to provision restarting celery tasks

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#554]
Refer log for exception that is thrown when this happens:

[po-celery.txt](https://github.com/aodn/chef/files/1259471/po-celery.txt)

Not sure why it was trying to do anything with celery anyway - nothing had changed apart from geonetwork harvester config.

**Comment by jonescc** [comment]
Appears to have been fixed by https://github.com/aodn/chef/pull/558

**Comment by jonescc** [comment]
Still an issue

**Comment by pblain** [comment]
Won't fix as it will be resolved by new pipeline
