### ISSUE TITLE
Should be able to do all po box operations using po-box.sh

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#561]
Currently the po-box.sh script only supports halt, ssh and provision  operations (the default).

Currently there is no way of starting a previously provisioned po-box as only the bin/po-box.sh script sets up ip addresses etc correctly.  This is a pain as you always have to provision when starting up the po-box.

Ideally other vagrant operations such as destroy should also be supported for consistency.   

The default operation being provision is also problematic as you can easily accidently shut the machine down and start a provision.

**Comment by pblain** [comment]
Moved to backlog https://github.com/aodn/backlog/issues/692
