### ISSUE TITLE
Geonetwork harvest in PO box should set all URLs to local

### ISSUE THREAD

**Issue by mhidas** [aodn/chef#562]
When geonetwork records are harvested into the po box (as per [instructions](https://github.com/aodn/chef/blob/master/doc/README.po-box.md#importing-vocabulariesharvesting-geonetwork-records)), all URLs for point of truth and geoserver layers should be updated to point to the services within the box. Otherwise there is a danger of working in the PO box without realising that we're actually looking at production data/metadata.

**Comment by pblain** [comment]
Moved to backlog https://github.com/aodn/backlog/issues/691
