### ISSUE TITLE
AWS cli version must be manually managed

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#590]
Deployed the new javaduck image changes to jenkins, but the docker login command didn't work because the aws cli version there is quite old and didn't support the -no-include-email  option used when testing in vagrant.

Should we be tracking the latest version of the aws cli or forcing upgrades in some way so I get the same result in prod as when testing?

**Comment by anguss00** [comment]
Closing this for now, cost benefit analysis failed the test ;-)
