### ISSUE TITLE
Can't add anymore s3 redirects for jenkins

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#591]
Apparently there is a limit of 50 and we've reached that.

**Comment by anguss00** [comment]
Feature request to fix this properly, adding a backlog item. In the meantine, we can prune s3 of artifacts that are not being used.

**Comment by jonescc** [comment]
Looks to me like we are using these redirects to provide public links to the latest version of some of our jenkins build artifacts.  For example, we provide links to our latest geonetwork and geoserver builds in our contributing documentation in portal help.   As far as I can tell chef and ebprep don't use these artifacts they go directly to jenkins.   Is this correct?

If so, then we probably don't need most of the redirects being setup - https://s3-ap-southeast-2.amazonaws.com/imos-binary/s3redirects.html

Perhaps in the first instance we can just remove all systest and edge redirects and in future only publish artifacts to s3 which need to be publicly accessible.   Any comments?

Also, it currently looks like we are using rules to specify redirects such as this.   There is a limit of 50 redirects than can be done this way.   A better way to perform redirects may be to use redirects at the object level - there's no limit to how many of these you can do.

**Comment by jonescc** [comment]
Pruning performed under https://github.com/aodn/chef/issues/591
