### ISSUE TITLE
Nagios not enabled when running 8-aws-syd.emii.org.au up from scratch

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#593]
When I run 8-aw-syd.emii.org.au up from scratch in vagrant, nagios is not enable as an apache site.

Took a little while for me to work this out.   Would be better if it was enabled as expected.

**Comment by lwgordonimos** [comment]
I was sure we had fixed this, but it may have gotten lost in a deleted PR or something. Will see if I can dig it up...

**Comment by lwgordonimos** [comment]
Yep, it was in a PR which was superseded by another one.

https://github.com/aodn/chef/pull/496/files#diff-4e094d5bc1d141265ccedbfd585290e3R51

New PR here https://github.com/aodn/chef/pull/594

**Comment by anguss00** [comment]
Closed as is fixed by #594
