### ISSUE TITLE
Request: consider supporting selection of specific SSL certificate databags

### ISSUE THREAD

**Issue by markhepburn** [aodn/chef#630]
There's a bit of an implicit assumption of a wildcard certificate.

The apache config template [uses the domain](https://github.com/aodn/chef/blob/a47f705cf2d728509fc4cc913633d1d09aac4f1e/cookbooks/imos_apache2/definitions/apache_for_webapp.rb#L42) as the name of the certificate, which means that you can't have multiple servers with separate certificates (under a common domain) in the same repo.

I think this use-case could be supported with an optional parameter, eg `cert_name` that could be used to override the value in the template if necessary (falling back to the domain as usual, of course)

**Comment by pblain** [comment]
Moved to the backlog for consideration: https://github.com/aodn/backlog/issues/752

@markhepburn - Features to be worked on are decided by a committee. This will get discussed at the next meeting but to be honest I don't like its chances. Too many competing requests. I have no objection to it though. We wouldn't reject a PR if you put one up.
