### ISSUE TITLE
PO box permission errors when developing v2 pipelines

### ISSUE THREAD

**Issue by anguss00** [aodn/chef#669]
Raised by @lbesnard 

Steps to reproduce:
Create new pipeline on po box, push file with permissions 644 and owned by projectofficer into incoming dir.

Expected behaviour:
File is picked up by the pipeline.

Observed behaviour:
File is not picked up, file has permissions error as cannot be safe deleted.

**Comment by lwgordonimos** [comment]
Closing as correct permissions should be on files pushed into pipeline
