### ISSUE TITLE
Can't run 13-aws-syd up from scratch in vagrant

### ISSUE THREAD

**Issue by jonescc** [aodn/chef#680]
Get an error installing pendulum for the compliance checker

==> 13-aws-syd.emii.org.au:     copying pendulum/tz/timezone_info.py -> build/lib.linux-x86_64-2.7/pendulum/tz
==> 13-aws-syd.emii.org.au:     error: can't copy 'pendulum/formatting': doesn't exist or not a regular file
==> 13-aws-syd.emii.org.au:     
==> 13-aws-syd.emii.org.au:     ----------------------------------------
==> 13-aws-syd.emii.org.au: STDERR: Failed building wheel for pendulum
==> 13-aws-syd.emii.org.au: Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-37wAdD/pendulum/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OXz9f1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-37wAdD/pendulum/
==> 13-aws-syd.emii.org.au: You are using pip version 8.1.1, however version 9.0.3 is available.
==> 13-aws-syd.emii.org.au: You should consider upgrading via the 'pip install --upgrade pip' command.
==> 13-aws-syd.emii.org.au: ---- End output of ["/usr/bin/python2.7", "-m", "pip.__main__", "install", "--requirement", "/var/chef/cache/requirements.txt"] ----
==> 13-aws-syd.emii.org.au: Ran ["/usr/bin/python2.7", "-m", "pip.__main__", "install", "--requirement", "/var/chef/cache/requirements.txt"] returned 1
==> 13-aws-syd.emii.org.au: [2018-03-29T14:50:12+11:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by anguss00** [comment]
Ha another day another jenkins error appears...
